#include <string.h>
#include <dirent.h>
#include "icon.h"

#define FULLNAME 34
const Icon full_names [] = {
    {".trash", "\uf1f8"}, // ""
    {".atom", "\ue764"}, // ""
    {".bashprofile", "\ue615"}, // ""
    {".bashrc", "\uf489"}, // ""
    {".git", "\uf1d3"}, // ""
    {".gitattributes", "\uf1d3"}, // ""
    {".gitconfig", "\uf1d3"}, // ""
    {".github", "\uf408"}, // ""
    {".gitignore", "\uf1d3"}, // ""
    {".gitmodules", "\uf1d3"}, // ""
    {".rvm", "\ue21e"}, // ""
    {".vimrc", "\ue62b"}, // ""
    {".vscode", "\ue70c"}, // ""
    {".zshrc", "\uf489"}, // ""
    {"bin", "\ue5fc"}, // ""
    {"config", "\ue5fc"}, // ""
    {"docker-compose.yml", "\uf308"}, // ""
    {"dockerfile", "\uf308"}, // ""
    {"ds_store", "\uf179"}, // ""
    {"gitignore_global", "\uf1d3"}, // ""
    {"gradle", "\ue70e"}, // ""
    {"gruntfile.coffee", "\ue611"}, // ""
    {"gruntfile.js", "\ue611"}, // ""
    {"gruntfile.ls", "\ue611"}, // ""
    {"gulpfile.coffee", "\ue610"}, // ""
    {"gulpfile.js", "\ue610"}, // ""
    {"gulpfile.ls", "\ue610"}, // ""
    {"hidden", "\uf023"}, // ""
    {"include", "\ue5fc"}, // ""
    {"lib", "\uf121"}, // ""
    {"localized", "\uf179"}, // ""
    {"node_modules", "\ue718"}, // ""
    {"npmignore", "\ue71e"}, // ""
    {"rubydoc", "\ue73b"}, // ""
};

#define EXTENSIONS 195
const Icon extensions [] = {
    {".7z", "\uf410"}, // ""
    {".apk", "\ue70e"}, // ""
    {".avi", "\uf03d"}, // ""
    {".avro", "\ue60b"}, // ""
    {".awk", "\uf489"}, // ""
    {".bash", "\uf489"}, // ""
    {".bash_history", "\uf489"}, // ""
    {".bash_profile", "\uf489"}, // ""
    {".bashrc", "\uf489"}, // ""
    {".bat", "\uf17a"}, // ""
    {".bio", "\uf910"}, // "蘿"
    {".bmp", "\uf1c5"}, // ""
    {".bz2", "\uf410"}, // ""
    {".c", "\ue61e"}, // ""
    {".c++", "\ue61d"}, // ""
    {".cc", "\ue61d"}, // ""
    {".cfg", "\ue615"}, // ""
    {".clj", "\ue768"}, // ""
    {".cljs", "\ue76a"}, // ""
    {".cls", "\ue600"}, // ""
    {".coffee", "\uf0f4"}, // ""
    {".conf", "\ue615"}, // ""
    {".cp", "\ue61d"}, // ""
    {".cpp", "\ue61d"}, // ""
    {".cs", "\uf81a"}, // ""
    {".cshtml", "\uf1fa"}, // ""
    {".csproj", "\uf81a"}, // ""
    {".csx", "\uf81a"}, // ""
    {".csh", "\uf489"}, // ""
    {".css", "\ue749"}, // ""
    {".csv", "\uf1c3"}, // ""
    {".cxx", "\ue61d"}, // ""
    {".d", "\ue7af"}, // ""
    {".dart", "\ue798"}, // ""
    {".db", "\uf1c0"}, // ""
    {".diff", "\uf440"}, // ""
    {".doc", "\uf1c2"}, // ""
    {".docx", "\uf1c2"}, // ""
    {".ds_store", "\uf179"}, // ""
    {".dump", "\uf1c0"}, // ""
    {".ebook", "\ue28b"}, // ""
    {".editorconfig", "\ue615"}, // ""
    {".ejs", "\ue618"}, // ""
    {".elm", "\ue62c"}, // ""
    {".env", "\uf462"}, // ""
    {".eot", "\uf031"}, // ""
    {".epub", "\ue28a"}, // ""
    {".erb", "\ue73b"}, // ""
    {".erl", "\ue7b1"}, // ""
    {".exe", "\uf17a"}, // ""
    {".ex", "\ue62d"}, // ""
    {".exs", "\ue62d"}, // ""
    {".fish", "\uf489"}, // ""
    {".flac", "\uf001"}, // ""
    {".flv", "\uf03d"}, // ""
    {".font", "\uf031"}, // ""
    {".fpl", "\uf910"}, // "蘿"
    {".gdoc", "\uf1c2"}, // ""
    {".gemfile", "\ue21e"}, // ""
    {".gemspec", "\ue21e"}, // ""
    {".gform", "\uf298"}, // ""
    {".gif", "\uf1c5"}, // ""
    {".git", "\uf1d3"}, // ""
    {".go", "\ue626"}, // ""
    {".gradle", "\ue70e"}, // ""
    {".gsheet", "\uf1c3"}, // ""
    {".gslides", "\uf1c4"}, // ""
    {".guardfile", "\ue21e"}, // ""
    {".gz", "\uf410"}, // ""
    {".h", "\uf0fd"}, // ""
    {".hbs", "\ue60f"}, // ""
    {".hpp", "\uf0fd"}, // ""
    {".hs", "\ue777"}, // ""
    {".htm", "\uf13b"}, // ""
    {".html", "\uf13b"}, // ""
    {".hxx", "\uf0fd"}, // ""
    {".ico", "\uf1c5"}, // ""
    {".image", "\uf1c5"}, // ""
    {".iml", "\ue7b5"}, // ""
    {".ini", "\ue615"}, // ""
    {".ipynb", "\ue606"}, // ""
    {".jar", "\ue204"}, // ""
    {".java", "\ue204"}, // ""
    {".jpeg", "\uf1c5"}, // ""
    {".jpg", "\uf1c5"}, // ""
    {".js", "\ue74e"}, // ""
    {".json", "\ue60b"}, // ""
    {".jsx", "\ue7ba"}, // ""
    {".jl", "\ue624"}, // ""
    {".ksh", "\uf489"}, // ""
    {".less", "\ue758"}, // ""
    {".lhs", "\ue777"}, // ""
    {".license", "\uf48a"}, // ""
    {".localized", "\uf179"}, // ""
    {".lock", "\uf023"}, // ""
    {".log", "\uf18d"}, // ""
    {".lua", "\ue620"}, // ""
    {".lz", "\uf410"}, // ""
    {".m3u", "\uf910"}, // "蘿"
    {".m3u8", "\uf910"}, // "蘿"
    {".m4a", "\uf001"}, // ""
    {".markdown", "\uf48a"}, // ""
    {".md", "\uf48a"}, // ""
    {".mkd", "\uf48a"}, // ""
    {".mkv", "\uf03d"}, // ""
    {".mobi", "\ue28b"}, // ""
    {".mov", "\uf03d"}, // ""
    {".mp3", "\uf001"}, // ""
    {".mp4", "\uf03d"}, // ""
    {".mustache", "\ue60f"}, // ""
    {".nix", "\uf313"}, // ""
    {".npmignore", "\ue71e"}, // ""
    {".opus", "\uf001"}, // ""
    {".ogg", "\uf001"}, // ""
    {".ogv", "\uf03d"}, // ""
    {".otf", "\uf031"}, // ""
    {".pdf", "\uf1c1"}, // ""
    {".php", "\ue73d"}, // ""
    {".pl", "\ue769"}, // ""
    {".pls", "\uf910"}, // "蘿"
    {".png", "\uf1c5"}, // ""
    {".ppt", "\uf1c4"}, // ""
    {".pptx", "\uf1c4"}, // ""
    {".procfile", "\ue21e"}, // ""
    {".properties", "\ue60b"}, // ""
    {".ps1", "\uf489"}, // ""
    {".psd", "\ue7b8"}, // ""
    {".pxm", "\uf1c5"}, // ""
    {".py", "\ue606"}, // ""
    {".pyc", "\ue606"}, // ""
    {".r", "\uf25d"}, // ""
    {".rakefile", "\ue21e"}, // ""
    {".rar", "\uf410"}, // ""
    {".razor", "\uf1fa"}, // ""
    {".rb", "\ue21e"}, // ""
    {".rdata", "\uf25d"}, // ""
    {".rdb", "\ue76d"}, // ""
    {".rdoc", "\uf48a"}, // ""
    {".rds", "\uf25d"}, // ""
    {".readme", "\uf48a"}, // ""
    {".rlib", "\ue7a8"}, // ""
    {".rmd", "\uf48a"}, // ""
    {".rs", "\ue7a8"}, // ""
    {".rspec", "\ue21e"}, // ""
    {".rspec_parallel", "\ue21e"}, // ""
    {".rspec_status", "\ue21e"}, // ""
    {".rss", "\uf09e"}, // ""
    {".ru", "\ue21e"}, // ""
    {".rubydoc", "\ue73b"}, // ""
    {".sass", "\ue603"}, // ""
    {".scala", "\ue737"}, // ""
    {".scss", "\ue749"}, // ""
    {".sh", "\uf489"}, // ""
    {".shell", "\uf489"}, // ""
    {".slim", "\ue73b"}, // ""
    {".sln", "\ue70c"}, // ""
    {".sql", "\uf1c0"}, // ""
    {".sqlite3", "\ue7c4"}, // ""
    {".styl", "\ue600"}, // ""
    {".stylus", "\ue600"}, // ""
    {".svg", "\uf1c5"}, // ""
    {".swift", "\ue755"}, // ""
    {".tar", "\uf410"}, // ""
    {".tex", "\ue600"}, // ""
    {".tiff", "\uf1c5"}, // ""
    {".ts", "\ue628"}, // ""
    {".tsx", "\ue7ba"}, // ""
    {".ttc", "\uf031"}, // ""
    {".ttf", "\uf031"}, // ""
    {".twig", "\ue61c"}, // ""
    {".txt", "\uf15c"}, // ""
    {".video", "\uf03d"}, // ""
    {".vim", "\ue62b"}, // ""
    {".vlc", "\uf910"}, // "蘿"
    {".vue", "\ufd42"}, // "﵂"
    {".wav", "\uf001"}, // ""
    {".webm", "\uf03d"}, // ""
    {".webp", "\uf1c5"}, // ""
    {".windows", "\uf17a"}, // ""
    {".wma", "\uf001"}, // ""
    {".wmv", "\uf03d"}, // ""
    {".wpl", "\uf910"}, // "蘿"
    {".woff", "\uf031"}, // ""
    {".woff2", "\uf031"}, // ""
    {".xls", "\uf1c3"}, // ""
    {".xlsx", "\uf1c3"}, // ""
    {".xml", "\ue619"}, // ""
    {".xul", "\ue619"}, // ""
    {".xz", "\uf410"}, // ""
    {".yaml", "\ue60b"}, // ""
    {".yml", "\ue60b"}, // ""
    {".zip", "\uf410"}, // ""
    {".zsh", "\uf489"}, // ""
    {".zsh-theme", "\uf489"}, // ""
    {".zshrc", "\uf489"}, // ""
};

const Icon get_icon_by_name(char * name) {
    Icon icon = strcmp(name, "dir") ?
        (Icon){.key = "file", .icon = "\uf016"}: // 
        (Icon){.key =  "dir", .icon = "\uf115"}; // 

    for (int i = 0; i < FULLNAME; i++)
        if (!strcmp(name, full_names[i].key)) return full_names[i];
    for (int i = 0; i < FULLNAME; i++) {
        char * curr_name = &name[strlen(name)-strlen(extensions[i].key)];
        if (!strcmp(curr_name, extensions[i].key)) return extensions[i];
    }

    return icon;
}

const Icon get_icon(struct dirent *file) {
    Icon icon = get_icon_by_name(file->d_name);
    if (strcmp(icon.key, "dir") && file->d_type != Directory)
        return icon;
    else
        return get_icon_by_name("dir");
}
